### PR TITLE
Added support for strikethrough, code, blockquote, separator and images

### PR DESCRIPTION
**Pull request by codenameakshay**
This PR adds support for more different types of markdown tags including these -
### Strikethrough
```~~text~~``` -> ~~text~~
### Code Blocks
text -> `text`
### Quote
```> text``` -> 
> text
### Separator
------
### Images
```text``` -> Alt text

### CODE REVIEW

**Comment by edouardouvrard** [comment]
hi @codenameakshay 
Thanks for your PR.
Could you fix the format  by running `flutter format --line-length 120 lib test` and push the change ?

**Comment by edouardouvrard** [comment]
Thanks @codenameakshay 
I will review and test in the next days 👍

**Comment by edouardouvrard** [comment]
@codenameakshay Could you update the readme with your change ?

**Comment by codenameakshay** [comment]
I have updated the readme file.

**Comment by guenth39** [comment]
@codenameakshay @edouardouvrard  Any update on this?

**Comment by codenameakshay** [comment]
I have updated everything, just waiting for @edouardouvrard to merge it.

**Comment by clemenceroumy** [comment]
Hi @guenth39, @codenameakshay, a new version of the package has been uploaded, it will be available in a few time. 
Thanks @codenameakshay for your contribution to this package :)

**Pull request merged**
